### ISSUE TITLE
idokep_alert is not available

### ISSUE THREAD

**Issue by gorcsev71** [tolnai/home_assistant_idokep_scraper#13]
The idokep_alert sensor is no longer available

**Comment by tolnai** [comment]
Amikor épp nincs riasztás, akkor a "#topalertbar" nincs az oldalon egyáltalán, tehát nincs mit abba a sensor-ba tenni. Lehetne ilyenkor "" üres szöveg végülis, a multiscrape on_error/default beállításaival próbálkoztam, de mintha nem működne:

```
      - unique_id: idokep_alert
        name: "Időkép figyelmeztetés"
        select: "#topalertbar > a:nth-child(1)"
        on_error:
          log: false
          value: default
          default: ""
```
